// webui/src/components/base/SecretInput.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Eye, EyeOff } from 'lucide-react'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'

interface SecretInputProps {
  id?: string
  value: string
  onChange: (value: string) => void
  required?: boolean
  placeholder?: string
  readOnly?: boolean
  revealDuration?: number // Auto-hide duration in ms, 0 = no auto-hide
}

/**
 * Get masked value showing only first and last 3 characters
 */
function getMaskedValue(val: string): string {
  if (!val || val.length <= 8) {
    return '•'.repeat(val?.length || 0)
  }
  const prefix = val.slice(0, 3)
  const suffix = val.slice(-3)
  const middle = '•'.repeat(Math.min(val.length - 6, 10))
  return prefix + middle + suffix
}

export function SecretInput({
  id,
  value,
  onChange,
  required = false,
  placeholder = '',
  readOnly = false,
  revealDuration = 5000,
}: SecretInputProps) {
  const [isRevealed, setIsRevealed] = useState(false)
  const revealTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const maskedValue = getMaskedValue(value)

  const toggleReveal = useCallback(() => {
    setIsRevealed((prev) => {
      const newValue = !prev

      // Clear previous timer
      if (revealTimerRef.current) {
        clearTimeout(revealTimerRef.current)
        revealTimerRef.current = null
      }

      // If revealing and auto-hide is enabled
      if (newValue && revealDuration > 0) {
        revealTimerRef.current = setTimeout(() => {
          setIsRevealed(false)
          revealTimerRef.current = null
        }, revealDuration)
      }

      return newValue
    })
  }, [revealDuration])

  // Cleanup timer on unmount
  useEffect(() => {
    return () => {
      if (revealTimerRef.current) {
        clearTimeout(revealTimerRef.current)
      }
    }
  }, [])

  return (
    <div className="relative flex items-center">
      {isRevealed ? (
        <Input
          type="text"
          id={id}
          required={required}
          readOnly={readOnly}
          placeholder={placeholder}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          autoComplete="off"
          spellCheck={false}
          className="pr-10"
        />
      ) : (
        <Input
          type="password"
          id={id}
          required={required}
          readOnly={readOnly}
          placeholder={placeholder || maskedValue}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          autoComplete="new-password"
          className="pr-10"
        />
      )}

      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="absolute right-1 h-7 w-7 opacity-60 hover:opacity-100"
            onClick={toggleReveal}
            aria-label={isRevealed ? 'Hide secret' : 'Reveal secret'}
          >
            {isRevealed ? (
              <EyeOff className="h-4 w-4" />
            ) : (
              <Eye className="h-4 w-4" />
            )}
          </Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          {isRevealed ? 'Hide' : 'Reveal'}
        </TooltipContent>
      </Tooltip>
    </div>
  )
}

// ui/src/components/base/SecretInput.svelte
<script>
    import { onDestroy } from "svelte";
    import tooltip from "@/actions/tooltip";

    export let id = "";
    export let value = "";
    export let required = false;
    export let placeholder = "";
    export let readonly = false;
    export let revealDuration = 5000; // 自动隐藏时间(ms)，0 表示不自动隐藏

    let isRevealed = false;
    let revealTimer = null;

    // 掩码显示：只显示前后各 3 个字符
    $: maskedValue = getMaskedValue(value);

    function getMaskedValue(val) {
        if (!val || val.length <= 8) {
            return "•".repeat(val?.length || 0);
        }
        const prefix = val.slice(0, 3);
        const suffix = val.slice(-3);
        const middle = "•".repeat(Math.min(val.length - 6, 10));
        return prefix + middle + suffix;
    }

    function toggleReveal() {
        isRevealed = !isRevealed;

        // 清除之前的定时器
        if (revealTimer) {
            clearTimeout(revealTimer);
            revealTimer = null;
        }

        // 如果显示明文且设置了自动隐藏时间
        if (isRevealed && revealDuration > 0) {
            revealTimer = setTimeout(() => {
                isRevealed = false;
                revealTimer = null;
            }, revealDuration);
        }
    }

    onDestroy(() => {
        if (revealTimer) {
            clearTimeout(revealTimer);
        }
    });
</script>

<div class="secret-input-wrapper">
    {#if isRevealed}
        <input
            type="text"
            {id}
            {required}
            {readonly}
            {placeholder}
            bind:value
            autocomplete="off"
            spellcheck="false"
        />
    {:else}
        <input
            type="password"
            {id}
            {required}
            {readonly}
            placeholder={placeholder || maskedValue}
            bind:value
            autocomplete="new-password"
        />
    {/if}

    <button
        type="button"
        class="btn btn-sm btn-circle btn-transparent reveal-btn"
        aria-label={isRevealed ? "Hide secret" : "Reveal secret"}
        use:tooltip={isRevealed ? "Hide" : "Reveal"}
        on:click={toggleReveal}
    >
        <i class={isRevealed ? "ri-eye-off-line" : "ri-eye-line"}></i>
    </button>
</div>

<style>
    .secret-input-wrapper {
        position: relative;
        display: flex;
        align-items: center;
    }
    .secret-input-wrapper input {
        flex: 1;
        padding-right: 40px;
    }
    .reveal-btn {
        position: absolute;
        right: 5px;
        opacity: 0.6;
    }
    .reveal-btn:hover {
        opacity: 1;
    }
</style>
