// ui-v2/src/components/SecretInput.tsx
/**
 * SecretInput - 密文输入组件
 *
 * 特性:
 * - 掩码显示（前后各3字符）
 * - Reveal 切换显示/隐藏
 * - 5秒自动隐藏
 */
import { useState, useEffect, useRef, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { Eye, EyeOff } from 'lucide-react'
import { cn, maskSecret } from '@/lib/utils'

export interface SecretInputProps {
  id?: string
  value: string
  onChange: (value: string) => void
  placeholder?: string
  required?: boolean
  disabled?: boolean
  readOnly?: boolean
  revealDuration?: number // 自动隐藏时间(ms)，默认 5000，0 表示不自动隐藏
  className?: string
}

export function SecretInput({
  id,
  value,
  onChange,
  placeholder,
  required = false,
  disabled = false,
  readOnly = false,
  revealDuration = 5000,
  className,
}: SecretInputProps) {
  const [isRevealed, setIsRevealed] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // 清除定时器
  const clearRevealTimer = useCallback(() => {
    if (timerRef.current) {
      clearTimeout(timerRef.current)
      timerRef.current = null
    }
  }, [])

  // 切换显示/隐藏
  const toggleReveal = useCallback(() => {
    setIsRevealed((prev) => {
      const newValue = !prev
      clearRevealTimer()

      // 如果显示明文且设置了自动隐藏时间
      if (newValue && revealDuration > 0) {
        timerRef.current = setTimeout(() => {
          setIsRevealed(false)
          timerRef.current = null
        }, revealDuration)
      }

      return newValue
    })
  }, [revealDuration, clearRevealTimer])

  // 组件卸载时清除定时器
  useEffect(() => {
    return () => {
      clearRevealTimer()
    }
  }, [clearRevealTimer])

  const maskedValue = maskSecret(value)

  return (
    <div className={cn('relative flex items-center', className)}>
      <Input
        id={id}
        type={isRevealed ? 'text' : 'password'}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder || (value ? maskedValue : '')}
        required={required}
        disabled={disabled}
        readOnly={readOnly}
        autoComplete={isRevealed ? 'off' : 'new-password'}
        spellCheck={false}
        className="pr-10"
        data-testid="secret-input"
      />
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className="absolute right-1 h-7 w-7 opacity-60 hover:opacity-100"
              onClick={toggleReveal}
              disabled={disabled}
              aria-label={isRevealed ? 'Hide secret' : 'Reveal secret'}
              data-testid="reveal-button"
            >
              {isRevealed ? (
                <EyeOff className="h-4 w-4" />
              ) : (
                <Eye className="h-4 w-4" />
              )}
            </Button>
          </TooltipTrigger>
          <TooltipContent>
            <p>{isRevealed ? 'Hide' : 'Reveal'}</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </div>
  )
}

// ui/src/components/base/SecretInput.svelte
<script>
    import { onDestroy } from "svelte";
    import tooltip from "@/actions/tooltip";

    export let id = "";
    export let value = "";
    export let required = false;
    export let placeholder = "";
    export let readonly = false;
    export let revealDuration = 5000; // 自动隐藏时间(ms)，0 表示不自动隐藏

    let isRevealed = false;
    let revealTimer = null;

    // 掩码显示：只显示前后各 3 个字符
    $: maskedValue = getMaskedValue(value);

    function getMaskedValue(val) {
        if (!val || val.length <= 8) {
            return "•".repeat(val?.length || 0);
        }
        const prefix = val.slice(0, 3);
        const suffix = val.slice(-3);
        const middle = "•".repeat(Math.min(val.length - 6, 10));
        return prefix + middle + suffix;
    }

    function toggleReveal() {
        isRevealed = !isRevealed;

        // 清除之前的定时器
        if (revealTimer) {
            clearTimeout(revealTimer);
            revealTimer = null;
        }

        // 如果显示明文且设置了自动隐藏时间
        if (isRevealed && revealDuration > 0) {
            revealTimer = setTimeout(() => {
                isRevealed = false;
                revealTimer = null;
            }, revealDuration);
        }
    }

    onDestroy(() => {
        if (revealTimer) {
            clearTimeout(revealTimer);
        }
    });
</script>

<div class="secret-input-wrapper">
    {#if isRevealed}
        <input
            type="text"
            {id}
            {required}
            {readonly}
            {placeholder}
            bind:value
            autocomplete="off"
            spellcheck="false"
        />
    {:else}
        <input
            type="password"
            {id}
            {required}
            {readonly}
            placeholder={placeholder || maskedValue}
            bind:value
            autocomplete="new-password"
        />
    {/if}

    <button
        type="button"
        class="btn btn-sm btn-circle btn-transparent reveal-btn"
        aria-label={isRevealed ? "Hide secret" : "Reveal secret"}
        use:tooltip={isRevealed ? "Hide" : "Reveal"}
        on:click={toggleReveal}
    >
        <i class={isRevealed ? "ri-eye-off-line" : "ri-eye-line"}></i>
    </button>
</div>

<style>
    .secret-input-wrapper {
        position: relative;
        display: flex;
        align-items: center;
    }
    .secret-input-wrapper input {
        flex: 1;
        padding-right: 40px;
    }
    .reveal-btn {
        position: absolute;
        right: 5px;
        opacity: 0.6;
    }
    .reveal-btn:hover {
        opacity: 1;
    }
</style>
