// webui/src/features/records/components/fields/SecretField.tsx
import type { CollectionField } from 'pocketbase'
import { SecretInput } from '@/components/base/SecretInput'
import { FormField } from '@/components/ui/FormField'
import { FieldLabel } from './FieldLabel'

interface SecretFieldProps {
  field: CollectionField
  value: string
  onChange: (value: string) => void
}

export function SecretField({ field, value, onChange }: SecretFieldProps) {
  const uniqueId = `field_${field.name}`

  return (
    <FormField name={field.name} className={field.required ? 'required' : ''}>
      <FieldLabel field={field} htmlFor={uniqueId} />
      <SecretInput
        id={uniqueId}
        required={field.required}
        value={value || ''}
        onChange={onChange}
      />
    </FormField>
  )
}

// ui/src/components/records/fields/SecretField.svelte
<script>
    import Field from "@/components/base/Field.svelte";
    import SecretInput from "@/components/base/SecretInput.svelte";
    import FieldLabel from "@/components/records/fields/FieldLabel.svelte";

    export let field;
    export let value = "";
</script>

<Field class="form-field {field.required ? 'required' : ''}" name={field.name} let:uniqueId>
    <FieldLabel {uniqueId} {field} />

    <SecretInput
        id={uniqueId}
        required={field.required}
        bind:value
    />
</Field>
