// ui-v2/src/features/traces/components/TraceList.tsx
/**
 * TraceList 组件
 * Trace 列表，支持分页和选择
 */
import { useCallback, useMemo } from 'react'
import {
  Loader2,
  Check,
  AlertTriangle,
  X,
  HelpCircle,
  ChevronLeft,
  ChevronRight,
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { ScrollArea } from '@/components/ui/scroll-area'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { useTraces } from '../hooks/useTraces'
import type { TraceEntry } from '../store'
import { formatDuration, getStatusColor } from '@/lib/traceUtils'
import dayjs from 'dayjs'

interface TraceListProps {
  onSelect?: (trace: TraceEntry) => void
  className?: string
}

export function TraceList({ onSelect, className }: TraceListProps) {
  const { traces, isLoading, currentPage, hasMore, loadTraces } = useTraces()

  // 计算总页数（简化版，实际应从 API 获取）
  const totalPages = useMemo(() => {
    return hasMore ? currentPage + 1 : currentPage
  }, [currentPage, hasMore])

  // 分页处理
  const handlePageChange = useCallback(
    (page: number) => {
      if (page >= 1 && page !== currentPage) {
        loadTraces(page, false)
      }
    },
    [currentPage, loadTraces]
  )

  // 行点击
  const handleRowClick = useCallback(
    (trace: TraceEntry) => {
      onSelect?.(trace)
    },
    [onSelect]
  )

  // 获取页码列表
  const pageNumbers = useMemo(() => {
    const pages: number[] = []
    const maxVisible = 5

    if (totalPages <= maxVisible) {
      for (let i = 1; i <= totalPages; i++) {
        pages.push(i)
      }
    } else {
      const start = Math.max(1, currentPage - Math.floor(maxVisible / 2))
      const end = Math.min(totalPages, start + maxVisible - 1)

      for (let i = start; i <= end; i++) {
        pages.push(i)
      }
    }

    return pages
  }, [currentPage, totalPages])

  return (
    <div className={cn('relative flex flex-col rounded-lg border bg-card', className)}>
      {/* 加载遮罩 */}
      {isLoading && (
        <div className="absolute inset-0 z-10 flex items-center justify-center bg-background/70 rounded-lg">
          <Loader2 className="h-8 w-8 animate-spin" />
        </div>
      )}

      {/* 空状态 */}
      {traces.length === 0 && !isLoading ? (
        <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
          <HelpCircle className="h-12 w-12 mb-4 opacity-50" />
          <p>没有找到符合条件的 Trace 记录</p>
        </div>
      ) : (
        <>
          <ScrollArea className="flex-1">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[100px]">Trace ID</TableHead>
                  <TableHead>操作名称</TableHead>
                  <TableHead className="w-[90px]">状态</TableHead>
                  <TableHead className="w-[150px]">开始时间</TableHead>
                  <TableHead className="w-[80px]">耗时</TableHead>
                  <TableHead className="w-[60px] text-center">Spans</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {traces.map((trace) => (
                  <TraceRow key={trace.id} trace={trace} onClick={handleRowClick} />
                ))}
              </TableBody>
            </Table>
          </ScrollArea>

          {/* 分页 */}
          {totalPages > 1 && (
            <div className="flex items-center justify-center gap-2 p-3 border-t">
              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                disabled={currentPage === 1}
                onClick={() => handlePageChange(currentPage - 1)}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>

              <div className="flex gap-1">
                {pageNumbers.map((page) => (
                  <Button
                    key={page}
                    variant={page === currentPage ? 'default' : 'ghost'}
                    size="sm"
                    className="h-8 w-8 p-0"
                    onClick={() => handlePageChange(page)}
                  >
                    {page}
                  </Button>
                ))}
              </div>

              <Button
                variant="outline"
                size="icon"
                className="h-8 w-8"
                disabled={currentPage === totalPages}
                onClick={() => handlePageChange(currentPage + 1)}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          )}
        </>
      )}
    </div>
  )
}

// Trace 行组件
interface TraceRowProps {
  trace: TraceEntry
  onClick: (trace: TraceEntry) => void
}

function TraceRow({ trace, onClick }: TraceRowProps) {
  const statusColor = getStatusColor(trace.status?.toString() || 'UNKNOWN')

  // 获取状态图标
  const StatusIcon = useMemo(() => {
    switch (trace.status) {
      case 200:
      case 'OK':
        return Check
      case 'ERROR':
      case 500:
        return AlertTriangle
      case 'CANCELLED':
        return X
      default:
        return HelpCircle
    }
  }, [trace.status])

  // 格式化时间
  const formattedTime = useMemo(() => {
    return dayjs(trace.created).format('YYYY-MM-DD HH:mm:ss')
  }, [trace.created])

  return (
    <TableRow className="cursor-pointer" onClick={() => onClick(trace)}>
      <TableCell>
        <code className="text-xs font-mono">{trace.id.slice(0, 8)}...</code>
      </TableCell>
      <TableCell className="truncate max-w-[300px]" title={trace.url}>
        {trace.method} {trace.url || '-'}
      </TableCell>
      <TableCell>
        <span
          className={cn(
            'inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-medium',
            statusColor
          )}
        >
          <StatusIcon className="h-3 w-3" />
          {trace.status}
        </span>
      </TableCell>
      <TableCell className="text-sm text-muted-foreground">{formattedTime}</TableCell>
      <TableCell className="font-mono text-sm">{formatDuration(trace.execTime * 1000)}</TableCell>
      <TableCell className="text-center">{(trace.data as any)?.span_count || 1}</TableCell>
    </TableRow>
  )
}

// ui/src/components/monitor/TraceList.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import Scroller from "@/components/base/Scroller.svelte";
    import FormattedDate from "@/components/base/FormattedDate.svelte";
    
    export let traces = [];
    export let totalItems = 0;
    export let isLoading = false;
    export let currentPage = 1;
    export let perPage = 50;

    const dispatch = createEventDispatcher();

    $: totalPages = Math.ceil(totalItems / perPage);

    function formatDuration(microseconds) {
        if (microseconds === null || microseconds === undefined) return "-";
        
        const ms = microseconds / 1000;
        if (ms < 1) {
            return `${microseconds}μs`;
        } else if (ms < 1000) {
            return `${ms.toFixed(1)}ms`;
        } else {
            return `${(ms / 1000).toFixed(2)}s`;
        }
    }

    function getStatusClass(status) {
        switch (status) {
            case "OK":
                return "status-success";
            case "ERROR":
                return "status-error";
            case "CANCELLED":
                return "status-cancelled";
            default:
                return "status-unknown";
        }
    }

    function getStatusIcon(status) {
        switch (status) {
            case "OK":
                return "ri-check-line";
            case "ERROR":
                return "ri-error-warning-line";
            case "CANCELLED":
                return "ri-close-line";
            default:
                return "ri-question-line";
        }
    }

    function handleTraceClick(trace) {
        dispatch("traceSelect", trace);
    }

    function handlePageChange(page) {
        if (page >= 1 && page <= totalPages && page !== currentPage) {
            dispatch("pageChange", page);
        }
    }

    function getPageNumbers() {
        const pages = [];
        const maxVisible = 5;
        
        if (totalPages <= maxVisible) {
            for (let i = 1; i <= totalPages; i++) {
                pages.push(i);
            }
        } else {
            const start = Math.max(1, currentPage - Math.floor(maxVisible / 2));
            const end = Math.min(totalPages, start + maxVisible - 1);
            
            for (let i = start; i <= end; i++) {
                pages.push(i);
            }
        }
        
        return pages;
    }
</script>

<div class="trace-list-wrapper">
    {#if isLoading}
        <div class="loading-overlay">
            <div class="loader" />
        </div>
    {/if}

    {#if traces.length === 0 && !isLoading}
        <div class="empty-list">
            <i class="ri-file-list-3-line" />
            <p>没有找到符合条件的 Trace 记录</p>
        </div>
    {:else}
        <Scroller class="trace-scroller">
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-id">Trace ID</th>
                        <th class="col-name">操作名称</th>
                        <th class="col-status">状态</th>
                        <th class="col-time">开始时间</th>
                        <th class="col-duration">耗时</th>
                        <th class="col-spans">Spans</th>
                    </tr>
                </thead>
                <tbody>
                    {#each traces as trace (trace.trace_id)}
                        <tr 
                            class="trace-row" 
                            on:click={() => handleTraceClick(trace)}
                            role="button"
                            tabindex="0"
                        >
                            <td class="col-id">
                                <code class="txt-mono">{trace.trace_id.slice(0, 8)}...</code>
                            </td>
                            <td class="col-name txt-ellipsis" title={trace.name}>
                                {trace.name || "-"}
                            </td>
                            <td class="col-status">
                                <span class="label {getStatusClass(trace.status)}">
                                    <i class="{getStatusIcon(trace.status)}" />
                                    {trace.status}
                                </span>
                            </td>
                            <td class="col-time">
                                <FormattedDate date={trace.start_time} />
                            </td>
                            <td class="col-duration txt-mono">
                                {formatDuration(trace.duration)}
                            </td>
                            <td class="col-spans txt-center">
                                {trace.span_count || 1}
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </Scroller>

        <!-- 分页控件 -->
        {#if totalPages > 1}
            <div class="pagination-footer">
                <button 
                    type="button"
                    class="btn btn-xs btn-secondary"
                    disabled={currentPage === 1}
                    on:click={() => handlePageChange(currentPage - 1)}
                >
                    <i class="ri-arrow-left-s-line" />
                </button>

                <div class="page-numbers">
                    {#each getPageNumbers() as page}
                        <button 
                            type="button"
                            class="btn btn-xs {page === currentPage ? 'btn-primary' : 'btn-hint'}"
                            on:click={() => handlePageChange(page)}
                        >
                            {page}
                        </button>
                    {/each}
                </div>

                <button 
                    type="button"
                    class="btn btn-xs btn-secondary"
                    disabled={currentPage === totalPages}
                    on:click={() => handlePageChange(currentPage + 1)}
                >
                    <i class="ri-arrow-right-s-line" />
                </button>
            </div>
        {/if}
    {/if}
</div>

<style>
    .trace-list-wrapper {
        display: flex;
        flex-direction: column;
        flex-grow: 1;
        min-height: 0;
        background: var(--baseColor);
        border-radius: var(--baseRadius);
        border: 1px solid var(--baseAlt2Color);
        position: relative;
    }

    .trace-list-wrapper :global(.trace-scroller) {
        flex-grow: 1;
        min-height: 0;
    }

    .loading-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(255, 255, 255, 0.7);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 10;
        border-radius: var(--baseRadius);
    }

    .empty-list {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        flex-grow: 1;
        padding: 40px 20px;
        color: var(--txtHintColor);
    }

    .empty-list i {
        font-size: 2.5em;
        margin-bottom: 12px;
        opacity: 0.5;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
        table-layout: fixed;
    }

    .table th {
        position: sticky;
        top: 0;
        background: var(--baseAlt1Color);
        padding: 10px 12px;
        text-align: left;
        font-weight: 600;
        font-size: var(--smFontSize);
        color: var(--txtHintColor);
        border-bottom: 1px solid var(--baseAlt2Color);
        white-space: nowrap;
        z-index: 1;
    }

    .table td {
        padding: 10px 12px;
        border-bottom: 1px solid var(--baseAlt2Color);
        font-size: var(--smFontSize);
    }

    .col-id { width: 100px; }
    .col-name { width: auto; }
    .col-status { width: 90px; }
    .col-time { width: 150px; }
    .col-duration { width: 80px; }
    .col-spans { width: 60px; }

    .trace-row {
        cursor: pointer;
        transition: background-color 0.15s ease;
    }

    .trace-row:hover {
        background: var(--baseAlt1Color);
    }

    .txt-mono {
        font-family: var(--monospaceFontFamily);
        font-size: 0.85em;
    }

    .txt-ellipsis {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .txt-center {
        text-align: center;
    }

    .label {
        display: inline-flex;
        align-items: center;
        gap: 3px;
        padding: 3px 6px;
        border-radius: var(--baseRadius);
        font-size: 0.75em;
        font-weight: 500;
    }

    .status-success {
        background: rgba(34, 197, 94, 0.1);
        color: var(--successColor);
    }

    .status-error {
        background: rgba(239, 68, 68, 0.1);
        color: var(--dangerColor);
    }

    .status-cancelled,
    .status-unknown {
        background: var(--baseAlt2Color);
        color: var(--txtHintColor);
    }

    .pagination-footer {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 6px;
        padding: 10px;
        border-top: 1px solid var(--baseAlt2Color);
        flex-shrink: 0;
    }

    .page-numbers {
        display: flex;
        gap: 3px;
    }

    @media (max-width: 768px) {
        .col-time,
        .col-spans {
            display: none;
        }

        .table th,
        .table td {
            padding: 8px 10px;
        }
    }
</style>
