// webui/src/features/traces/components/TraceDetail.tsx
/**
 * Trace 详情面板
 * 瀑布图展示 Spans 调用链
 */
import { useState, useMemo } from 'react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { X, ChevronRight, ChevronDown, Loader2 } from 'lucide-react'
import type { Span, SpanStatus } from '../store'

interface Props {
  traceId: string | null
  spans: Span[]
  isLoading: boolean
  onClose: () => void
}

interface SpanNode extends Span {
  children: SpanNode[]
  level: number
}

/**
 * 格式化延迟
 */
function formatDuration(microseconds: number | null | undefined): string {
  if (microseconds === null || microseconds === undefined) return '-'
  
  const ms = microseconds / 1000
  if (ms < 1) {
    return `${microseconds}μs`
  } else if (ms < 1000) {
    return `${ms.toFixed(1)}ms`
  } else {
    return `${(ms / 1000).toFixed(2)}s`
  }
}

/**
 * 获取状态样式
 */
function getStatusStyle(status: SpanStatus): string {
  switch (status) {
    case 'OK':
      return 'bg-blue-500'
    case 'ERROR':
      return 'bg-red-500'
    case 'CANCELLED':
      return 'bg-slate-400'
    default:
      return 'bg-slate-300'
  }
}

/**
 * 状态徽章
 */
function StatusBadge({ status }: { status: SpanStatus }) {
  const styles: Record<SpanStatus, string> = {
    OK: 'bg-blue-100 text-blue-700',
    ERROR: 'bg-red-100 text-red-700',
    CANCELLED: 'bg-slate-100 text-slate-600',
    UNSET: 'bg-slate-100 text-slate-500',
  }

  return (
    <Badge variant="secondary" className={`${styles[status]} text-[10px] px-1.5 py-0`}>
      {status}
    </Badge>
  )
}

/**
 * 单个 Span 行
 */
function SpanRow({
  span,
  isExpanded,
  hasChildren,
  onToggle,
  minStartTime,
  totalDuration,
}: {
  span: SpanNode
  isExpanded: boolean
  hasChildren: boolean
  onToggle: () => void
  minStartTime: number
  totalDuration: number
}) {
  const leftPercent = ((span.start_time - minStartTime) / totalDuration) * 100
  const widthPercent = (span.duration / totalDuration) * 100

  return (
    <div className="border-b border-slate-100 last:border-b-0">
      <div className="flex items-center py-2" style={{ marginLeft: `${span.level * 16}px` }}>
        {/* 展开按钮 */}
        <div className="w-5 flex-shrink-0">
          {hasChildren && (
            <button
              type="button"
              onClick={onToggle}
              className="text-slate-400 hover:text-slate-600"
            >
              {isExpanded ? (
                <ChevronDown className="w-4 h-4" />
              ) : (
                <ChevronRight className="w-4 h-4" />
              )}
            </button>
          )}
        </div>

        {/* Span 信息 */}
        <div className="w-48 flex-shrink-0 flex items-center gap-2 pr-2">
          <span className="text-xs text-slate-900 truncate flex-1" title={span.name}>
            {span.name}
          </span>
          <span className="text-[10px] font-mono text-slate-400 flex-shrink-0">
            {formatDuration(span.duration)}
          </span>
          <StatusBadge status={span.status} />
        </div>

        {/* 瀑布图时间条 */}
        <div className="flex-1 relative h-5 bg-slate-100 rounded-sm mx-2">
          <div
            className={`absolute top-0.5 bottom-0.5 rounded-sm ${getStatusStyle(span.status)}`}
            style={{
              left: `${leftPercent}%`,
              width: `${Math.max(widthPercent, 0.5)}%`,
            }}
          />
        </div>
      </div>

      {/* 属性展示 */}
      {span.attributes && Object.keys(span.attributes).length > 0 && (
        <div className="ml-5 mr-4 mb-2 px-3 py-2 bg-slate-50 rounded text-xs" style={{ marginLeft: `${span.level * 16 + 20}px` }}>
          {Object.entries(span.attributes).map(([key, value]) => (
            <div key={key} className="flex gap-2 py-0.5">
              <span className="text-slate-500 min-w-[100px]">{key}:</span>
              <span className="text-slate-700 break-all">{String(value)}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export function TraceDetail({ traceId, spans, isLoading, onClose }: Props) {
  const [expandedSpans, setExpandedSpans] = useState<Set<string>>(new Set())

  // 构建层级结构
  const { spanHierarchy, minStartTime, totalDuration } = useMemo(() => {
    if (spans.length === 0) {
      return { spanHierarchy: [], minStartTime: 0, totalDuration: 1 }
    }

    // 计算时间范围
    const startTimes = spans.map(s => s.start_time)
    const endTimes = spans.map(s => s.start_time + s.duration)
    const minStart = Math.min(...startTimes)
    const maxEnd = Math.max(...endTimes)
    const total = maxEnd - minStart

    // 构建父子关系
    const spanMap = new Map<string, SpanNode>()
    spans.forEach(span => {
      spanMap.set(span.span_id, { ...span, children: [], level: 0 })
    })

    const rootSpans: SpanNode[] = []
    spans.forEach(span => {
      const spanNode = spanMap.get(span.span_id)!
      if (span.parent_id && spanMap.has(span.parent_id)) {
        const parent = spanMap.get(span.parent_id)!
        parent.children.push(spanNode)
        spanNode.level = parent.level + 1
      } else {
        rootSpans.push(spanNode)
      }
    })

    // 扁平化（考虑展开状态）
    const flattenSpans = (nodes: SpanNode[], level = 0): SpanNode[] => {
      const result: SpanNode[] = []
      nodes.forEach(node => {
        node.level = level
        result.push(node)
        if (expandedSpans.has(node.span_id) && node.children.length > 0) {
          result.push(...flattenSpans(node.children, level + 1))
        }
      })
      return result
    }

    return {
      spanHierarchy: flattenSpans(rootSpans),
      minStartTime: minStart,
      totalDuration: total || 1,
    }
  }, [spans, expandedSpans])

  const toggleSpan = (spanId: string) => {
    setExpandedSpans(prev => {
      const next = new Set(prev)
      if (next.has(spanId)) {
        next.delete(spanId)
      } else {
        next.add(spanId)
      }
      return next
    })
  }

  // 检查 span 是否有子节点
  const spanMap = useMemo(() => {
    const map = new Map<string, SpanNode>()
    spans.forEach(span => {
      map.set(span.span_id, { ...span, children: [], level: 0 })
    })
    spans.forEach(span => {
      if (span.parent_id && map.has(span.parent_id)) {
        map.get(span.parent_id)!.children.push(map.get(span.span_id)!)
      }
    })
    return map
  }, [spans])

  const hasChildren = (spanId: string) => {
    return (spanMap.get(spanId)?.children.length ?? 0) > 0
  }

  return (
    <div
      className={`fixed right-0 top-0 h-full w-[500px] bg-white border-l border-slate-200 shadow-xl transform transition-transform duration-300 ease-out z-20 ${
        traceId ? 'translate-x-0' : 'translate-x-full'
      }`}
    >
      {traceId && (
        <div className="h-full flex flex-col">
          {/* 头部 */}
          <div className="h-14 px-4 border-b border-slate-200 flex items-center justify-between bg-slate-50/80 backdrop-blur-sm flex-shrink-0">
            <div className="min-w-0">
              <h3 className="text-sm font-medium text-slate-900">Trace 详情</h3>
              <code className="text-xs text-slate-500 font-mono">{traceId}</code>
            </div>
            <Button variant="ghost" size="sm" onClick={onClose} className="h-8 w-8 p-0 flex-shrink-0">
              <X className="w-4 h-4" />
            </Button>
          </div>

          {/* 内容 */}
          <div className="flex-1 overflow-auto">
            {isLoading ? (
              <div className="flex flex-col items-center justify-center h-64 text-slate-400">
                <Loader2 className="w-6 h-6 animate-spin mb-2" />
                <span className="text-sm">加载 Trace 详情中...</span>
              </div>
            ) : spans.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-64 text-slate-400">
                <span className="text-sm">此 Trace 没有 Span 数据</span>
              </div>
            ) : (
              <>
                {/* 瀑布图头部 */}
                <div className="px-4 py-2 border-b border-slate-100 bg-slate-50/50">
                  <div className="flex justify-between text-xs text-slate-500">
                    <span>总耗时: {formatDuration(totalDuration)}</span>
                    <span>Span 数量: {spans.length}</span>
                  </div>
                  {/* 时间轴 */}
                  <div className="flex justify-between text-[10px] text-slate-400 mt-2 ml-[calc(16px+12rem+0.5rem)] mr-2">
                    <span>0ms</span>
                    <span>{formatDuration(totalDuration)}</span>
                  </div>
                </div>

                {/* Span 列表 */}
                <div className="px-2">
                  {spanHierarchy.map(span => (
                    <SpanRow
                      key={span.span_id}
                      span={span}
                      isExpanded={expandedSpans.has(span.span_id)}
                      hasChildren={hasChildren(span.span_id)}
                      onToggle={() => toggleSpan(span.span_id)}
                      minStartTime={minStartTime}
                      totalDuration={totalDuration}
                    />
                  ))}
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// ui/src/components/monitor/TraceDetail.svelte
<script>
    import { createEventDispatcher, onMount } from "svelte";
    import ApiClient from "@/utils/ApiClient";
    import FormattedDate from "@/components/base/FormattedDate.svelte";
    
    export let trace;

    const dispatch = createEventDispatcher();

    let spans = [];
    let isLoading = true;
    let error = null;
    let expandedSpans = new Set();

    // 瀑布图相关
    let totalDuration = 0;
    let minStartTime = 0;
    let spanHierarchy = [];

    onMount(async () => {
        await loadTraceDetails();
    });

    async function loadTraceDetails() {
        try {
            error = null;
            isLoading = true;
            
            const response = await ApiClient.send(`/api/traces/${trace.trace_id}`, {
                method: "GET"
            });
            
            spans = response.items || [];
            buildSpanHierarchy();
        } catch (err) {
            error = err.message || "加载 Trace 详情失败";
        } finally {
            isLoading = false;
        }
    }

    function buildSpanHierarchy() {
        if (spans.length === 0) return;

        // 计算时间范围
        const startTimes = spans.map(s => new Date(s.start_time).getTime());
        const endTimes = spans.map(s => new Date(s.start_time).getTime() + (s.duration / 1000));
        
        minStartTime = Math.min(...startTimes);
        const maxEndTime = Math.max(...endTimes);
        totalDuration = maxEndTime - minStartTime;

        // 构建父子关系
        const spanMap = new Map();
        spans.forEach(span => {
            spanMap.set(span.span_id, { ...span, children: [], level: 0 });
        });

        const rootSpans = [];
        spans.forEach(span => {
            const spanNode = spanMap.get(span.span_id);
            if (span.parent_id && spanMap.has(span.parent_id)) {
                const parent = spanMap.get(span.parent_id);
                parent.children.push(spanNode);
                spanNode.level = parent.level + 1;
            } else {
                rootSpans.push(spanNode);
            }
        });

        // 扁平化层级结构用于显示
        spanHierarchy = [];
        function flattenSpans(spans, level = 0) {
            spans.forEach(span => {
                span.level = level;
                spanHierarchy.push(span);
                if (expandedSpans.has(span.span_id) && span.children.length > 0) {
                    flattenSpans(span.children, level + 1);
                }
            });
        }
        flattenSpans(rootSpans);
    }

    function formatDuration(microseconds) {
        if (microseconds === null || microseconds === undefined) return "-";
        
        const ms = microseconds / 1000;
        if (ms < 1) {
            return `${microseconds}μs`;
        } else if (ms < 1000) {
            return `${ms.toFixed(1)}ms`;
        } else {
            return `${(ms / 1000).toFixed(2)}s`;
        }
    }

    function getStatusClass(status) {
        switch (status) {
            case "OK":
                return "status-success";
            case "ERROR":
                return "status-error";
            case "CANCELLED":
                return "status-cancelled";
            default:
                return "status-unknown";
        }
    }

    function getSpanBarStyle(span) {
        const startTime = new Date(span.start_time).getTime();
        const duration = span.duration / 1000; // 转换为毫秒
        
        const leftPercent = ((startTime - minStartTime) / totalDuration) * 100;
        const widthPercent = (duration / totalDuration) * 100;
        
        return `left: ${leftPercent}%; width: ${Math.max(widthPercent, 0.5)}%;`;
    }

    function toggleSpanExpansion(spanId) {
        if (expandedSpans.has(spanId)) {
            expandedSpans.delete(spanId);
        } else {
            expandedSpans.add(spanId);
        }
        expandedSpans = expandedSpans; // 触发响应式更新
        buildSpanHierarchy(); // 重新构建显示层级
    }

    function handleClose() {
        dispatch("close");
    }
</script>

<div class="trace-detail-overlay" on:click={handleClose}>
    <div class="trace-detail-modal" on:click|stopPropagation>
        <header class="modal-header">
            <div class="header-content">
                <h2>Trace 详情</h2>
                <div class="trace-info">
                    <span class="trace-id">
                        <strong>Trace ID:</strong> 
                        <code>{trace.trace_id}</code>
                    </span>
                    <span class="trace-operation">
                        <strong>操作:</strong> {trace.name || "-"}
                    </span>
                </div>
            </div>
            <button type="button" class="btn btn-sm btn-secondary" on:click={handleClose}>
                <i class="ri-close-line" />
                关闭
            </button>
        </header>

        <div class="modal-body">
            {#if error}
                <div class="alert alert-danger">
                    <i class="ri-error-warning-line" />
                    <span>{error}</span>
                </div>
            {:else if isLoading}
                <div class="loading-placeholder">
                    <div class="loader" />
                    <span>加载 Trace 详情中...</span>
                </div>
            {:else if spans.length === 0}
                <div class="empty-state">
                    <i class="ri-file-list-3-line" />
                    <p>此 Trace 没有 Span 数据</p>
                </div>
            {:else}
                <!-- 瀑布图 -->
                <div class="waterfall-chart">
                    <div class="chart-header">
                        <h3>调用链瀑布图</h3>
                        <div class="chart-info">
                            总耗时: {formatDuration(totalDuration * 1000)} | 
                            Span 数量: {spans.length}
                        </div>
                    </div>

                    <div class="chart-content">
                        <!-- 时间轴 -->
                        <div class="timeline">
                            <div class="timeline-scale">
                                <span>0ms</span>
                                <span>{formatDuration(totalDuration * 1000)}</span>
                            </div>
                        </div>

                        <!-- Span 列表 -->
                        <div class="spans-container">
                            {#each spanHierarchy as span (span.span_id)}
                                <div class="span-row" style="margin-left: {span.level * 20}px;">
                                    <div class="span-info">
                                        <div class="span-header">
                                            {#if span.children && span.children.length > 0}
                                                <button 
                                                    class="expand-btn" 
                                                    on:click={() => toggleSpanExpansion(span.span_id)}
                                                >
                                                    <i class="{expandedSpans.has(span.span_id) ? 'ri-arrow-down-s-line' : 'ri-arrow-right-s-line'}" />
                                                </button>
                                            {:else}
                                                <div class="expand-placeholder"></div>
                                            {/if}
                                            
                                            <span class="span-name" title={span.name}>{span.name}</span>
                                            <span class="span-duration">{formatDuration(span.duration)}</span>
                                            <span class="status-badge {getStatusClass(span.status)}">
                                                {span.status}
                                            </span>
                                        </div>
                                        
                                        <div class="span-timeline">
                                            <div class="span-bar {getStatusClass(span.status)}" style={getSpanBarStyle(span)}></div>
                                        </div>
                                    </div>
                                    
                                    <!-- Span 属性展示 -->
                                    {#if span.attributes && Object.keys(span.attributes).length > 0}
                                        <div class="span-attributes">
                                            {#each Object.entries(span.attributes) as [key, value]}
                                                <div class="attribute-item">
                                                    <span class="attribute-key">{key}:</span>
                                                    <span class="attribute-value">{value}</span>
                                                </div>
                                            {/each}
                                        </div>
                                    {/if}
                                </div>
                            {/each}
                        </div>
                    </div>
                </div>
            {/if}
        </div>
    </div>
</div>



<style>
    .trace-detail-overlay {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        align-items: center;
        justify-content: center;
        z-index: 1000;
        padding: 20px;
    }

    .trace-detail-modal {
        background: var(--baseColor);
        border-radius: var(--baseRadius);
        border: 1px solid var(--baseAlt2Color);
        max-width: 1200px;
        width: 100%;
        max-height: 90vh;
        display: flex;
        flex-direction: column;
        box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
    }

    .modal-header {
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        padding: 20px;
        border-bottom: 1px solid var(--baseAlt2Color);
        gap: 20px;
    }

    .header-content h2 {
        margin: 0 0 8px 0;
        font-size: 1.25em;
        color: var(--txtPrimaryColor);
    }

    .trace-info {
        display: flex;
        flex-direction: column;
        gap: 4px;
        font-size: 0.875em;
    }

    .trace-id code {
        background: var(--baseAlt1Color);
        padding: 2px 6px;
        border-radius: 3px;
        font-family: monospace;
        font-size: 0.9em;
    }

    .modal-body {
        flex: 1;
        overflow: hidden;
        display: flex;
        flex-direction: column;
    }

    .loading-placeholder {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 60px 20px;
        color: var(--txtHintColor);
    }

    .empty-state {
        text-align: center;
        padding: 60px 20px;
        color: var(--txtHintColor);
    }

    .empty-state i {
        font-size: 3em;
        margin-bottom: 16px;
        opacity: 0.5;
    }

    .waterfall-chart {
        flex: 1;
        display: flex;
        flex-direction: column;
        overflow: hidden;
    }

    .chart-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        border-bottom: 1px solid var(--baseAlt2Color);
    }

    .chart-header h3 {
        margin: 0;
        font-size: 1.1em;
        color: var(--txtPrimaryColor);
    }

    .chart-info {
        font-size: 0.875em;
        color: var(--txtHintColor);
    }

    .chart-content {
        flex: 1;
        overflow: auto;
        padding: 20px;
    }

    .timeline {
        margin-bottom: 16px;
        padding: 0 200px 0 20px;
    }

    .timeline-scale {
        display: flex;
        justify-content: space-between;
        font-size: 0.75em;
        color: var(--txtHintColor);
        border-bottom: 1px solid var(--baseAlt2Color);
        padding-bottom: 4px;
    }

    .spans-container {
        display: flex;
        flex-direction: column;
        gap: 2px;
    }

    .span-row {
        display: flex;
        flex-direction: column;
    }

    .span-info {
        display: flex;
        align-items: center;
        padding: 8px 0;
        border-bottom: 1px solid var(--baseAlt2Color);
    }

    .span-attributes {
        margin-left: 24px;
        padding: 8px 12px;
        background: var(--baseAlt1Color);
        border-radius: 4px;
        margin-top: 4px;
        margin-bottom: 8px;
        font-size: 0.8em;
    }

    .attribute-item {
        display: flex;
        gap: 8px;
        margin-bottom: 2px;
    }

    .attribute-key {
        font-weight: 500;
        color: var(--txtHintColor);
        min-width: 120px;
    }

    .attribute-value {
        color: var(--txtPrimaryColor);
        word-break: break-all;
    }

    .span-header {
        display: flex;
        align-items: center;
        gap: 8px;
        width: 200px;
        flex-shrink: 0;
        font-size: 0.875em;
    }

    .expand-btn {
        background: none;
        border: none;
        padding: 2px;
        cursor: pointer;
        color: var(--txtHintColor);
        width: 16px;
        height: 16px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .expand-placeholder {
        width: 16px;
        height: 16px;
    }

    .span-name {
        flex: 1;
        font-weight: 500;
        color: var(--txtPrimaryColor);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .span-duration {
        font-family: monospace;
        font-size: 0.8em;
        color: var(--txtHintColor);
        margin-right: 8px;
    }

    .span-timeline {
        flex: 1;
        position: relative;
        height: 20px;
        background: var(--baseAlt1Color);
        border-radius: 2px;
        margin-left: 20px;
    }

    .span-bar {
        position: absolute;
        top: 2px;
        bottom: 2px;
        border-radius: 2px;
        min-width: 2px;
    }

    .span-bar.status-success {
        background: var(--successColor);
    }

    .span-bar.status-error {
        background: var(--dangerColor);
    }

    .span-bar.status-cancelled {
        background: var(--txtHintColor);
    }

    .span-bar.status-unknown {
        background: var(--txtHintColor);
    }

    .status-badge {
        padding: 2px 6px;
        border-radius: 8px;
        font-size: 0.7em;
        font-weight: 500;
    }

    .status-success {
        background: rgba(34, 197, 94, 0.1);
        color: var(--successColor);
    }

    .status-error {
        background: rgba(239, 68, 68, 0.1);
        color: var(--dangerColor);
    }

    .status-cancelled {
        background: rgba(156, 163, 175, 0.1);
        color: var(--txtHintColor);
    }

    .status-unknown {
        background: rgba(156, 163, 175, 0.1);
        color: var(--txtHintColor);
    }

    @media (max-width: 768px) {
        .trace-detail-overlay {
            padding: 10px;
        }

        .modal-header {
            flex-direction: column;
            gap: 12px;
            align-items: flex-start;
        }

        .span-header {
            width: 150px;
        }

        .timeline {
            padding: 0 150px 0 10px;
        }
    }
</style>
