// webui/src/features/traces/components/TraceList.tsx
/**
 * Trace 列表
 * 显示 Trace ID、操作名称、状态、时间、耗时、Spans 数量
 */
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Loader2, ChevronLeft, ChevronRight, Check, X, AlertCircle } from 'lucide-react'
import type { Span, SpanStatus } from '../store'

interface Props {
  traces: Span[]
  isLoading: boolean
  currentPage: number
  totalItems: number
  perPage: number
  totalPages: number
  activeTraceId: string | null
  onTraceSelect: (traceId: string) => void
  onPageChange: (page: number) => void
}

/**
 * 格式化时间戳（微秒 -> 日期时间）
 */
function formatTimestamp(microseconds: number): string {
  const date = new Date(microseconds / 1000)
  return date.toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
}

/**
 * 格式化延迟（微秒 -> 可读格式）
 */
function formatDuration(microseconds: number | null | undefined): string {
  if (microseconds === null || microseconds === undefined) return '-'
  
  const ms = microseconds / 1000
  if (ms < 1) {
    return `${microseconds}μs`
  } else if (ms < 1000) {
    return `${ms.toFixed(1)}ms`
  } else {
    return `${(ms / 1000).toFixed(2)}s`
  }
}

/**
 * 状态图标
 */
function StatusIcon({ status }: { status: SpanStatus }) {
  switch (status) {
    case 'OK':
      return <Check className="w-3.5 h-3.5" />
    case 'ERROR':
      return <X className="w-3.5 h-3.5" />
    case 'CANCELLED':
      return <AlertCircle className="w-3.5 h-3.5" />
    default:
      return null
  }
}

/**
 * 状态徽章
 */
function StatusBadge({ status }: { status: SpanStatus }) {
  const styles: Record<SpanStatus, string> = {
    OK: 'bg-blue-100 text-blue-700',
    ERROR: 'bg-red-100 text-red-700',
    CANCELLED: 'bg-slate-100 text-slate-600',
    UNSET: 'bg-slate-100 text-slate-500',
  }

  return (
    <Badge variant="secondary" className={`${styles[status]} text-xs gap-1`}>
      <StatusIcon status={status} />
      {status}
    </Badge>
  )
}

/**
 * 分页页码
 */
function getPageNumbers(currentPage: number, totalPages: number): number[] {
  const pages: number[] = []
  const maxVisible = 5
  
  if (totalPages <= maxVisible) {
    for (let i = 1; i <= totalPages; i++) {
      pages.push(i)
    }
  } else {
    const start = Math.max(1, currentPage - Math.floor(maxVisible / 2))
    const end = Math.min(totalPages, start + maxVisible - 1)
    
    for (let i = start; i <= end; i++) {
      pages.push(i)
    }
  }
  
  return pages
}

export function TraceList({
  traces,
  isLoading,
  currentPage,
  totalItems,
  perPage,
  totalPages,
  activeTraceId,
  onTraceSelect,
  onPageChange,
}: Props) {
  if (isLoading && traces.length === 0) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
      </div>
    )
  }

  if (traces.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-slate-400">
        <AlertCircle className="w-10 h-10 mb-3 opacity-50" />
        <p>没有找到符合条件的 Trace 记录</p>
      </div>
    )
  }

  return (
    <div className="relative">
      {/* 加载遮罩 */}
      {isLoading && (
        <div className="absolute inset-0 bg-white/70 flex items-center justify-center z-10">
          <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
        </div>
      )}

      {/* 表格 */}
      <Table>
        <TableHeader>
          <TableRow className="bg-slate-50/50">
            <TableHead className="w-24 text-xs">Trace ID</TableHead>
            <TableHead className="text-xs">操作名称</TableHead>
            <TableHead className="w-20 text-xs">状态</TableHead>
            <TableHead className="w-32 text-xs">开始时间</TableHead>
            <TableHead className="w-20 text-xs text-right">耗时</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {traces.map((trace) => (
            <TableRow
              key={trace.trace_id + trace.span_id}
              className={`cursor-pointer transition-colors ${
                activeTraceId === trace.trace_id
                  ? 'bg-blue-50 hover:bg-blue-50'
                  : 'hover:bg-slate-50'
              }`}
              onClick={() => onTraceSelect(trace.trace_id)}
            >
              <TableCell className="py-2">
                <code className="text-xs font-mono text-slate-600">
                  {trace.trace_id.slice(0, 8)}...
                </code>
              </TableCell>
              <TableCell className="py-2">
                <span className="text-sm text-slate-900 truncate block max-w-md" title={trace.name}>
                  {trace.name || '-'}
                </span>
              </TableCell>
              <TableCell className="py-2">
                <StatusBadge status={trace.status} />
              </TableCell>
              <TableCell className="py-2 text-xs text-slate-500">
                {formatTimestamp(trace.start_time)}
              </TableCell>
              <TableCell className="py-2 text-xs font-mono text-slate-600 text-right">
                {formatDuration(trace.duration)}
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>

      {/* 分页 */}
      {totalPages > 1 && (
        <div className="flex justify-center items-center gap-1 py-3 border-t border-slate-100">
          <Button
            variant="ghost"
            size="sm"
            disabled={currentPage === 1}
            onClick={() => onPageChange(currentPage - 1)}
            className="h-7 w-7 p-0"
          >
            <ChevronLeft className="w-4 h-4" />
          </Button>

          {getPageNumbers(currentPage, totalPages).map((page) => (
            <Button
              key={page}
              variant={page === currentPage ? 'default' : 'ghost'}
              size="sm"
              onClick={() => onPageChange(page)}
              className={`h-7 w-7 p-0 text-xs ${
                page === currentPage ? 'bg-blue-500 hover:bg-blue-600' : ''
              }`}
            >
              {page}
            </Button>
          ))}

          <Button
            variant="ghost"
            size="sm"
            disabled={currentPage === totalPages}
            onClick={() => onPageChange(currentPage + 1)}
            className="h-7 w-7 p-0"
          >
            <ChevronRight className="w-4 h-4" />
          </Button>
        </div>
      )}
    </div>
  )
}

// ui/src/components/monitor/TraceList.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import FormattedDate from "@/components/base/FormattedDate.svelte";
    
    export let traces = [];
    export let totalItems = 0;
    export let isLoading = false;
    export let currentPage = 1;
    export let perPage = 50;

    const dispatch = createEventDispatcher();

    $: totalPages = Math.ceil(totalItems / perPage);

    function formatDuration(microseconds) {
        if (microseconds === null || microseconds === undefined) return "-";
        
        const ms = microseconds / 1000;
        if (ms < 1) {
            return `${microseconds}μs`;
        } else if (ms < 1000) {
            return `${ms.toFixed(1)}ms`;
        } else {
            return `${(ms / 1000).toFixed(2)}s`;
        }
    }

    function getStatusClass(status) {
        switch (status) {
            case "OK":
                return "status-success";
            case "ERROR":
                return "status-error";
            case "CANCELLED":
                return "status-cancelled";
            default:
                return "status-unknown";
        }
    }

    function getStatusIcon(status) {
        switch (status) {
            case "OK":
                return "ri-check-line";
            case "ERROR":
                return "ri-error-warning-line";
            case "CANCELLED":
                return "ri-close-line";
            default:
                return "ri-question-line";
        }
    }

    function handleTraceClick(trace) {
        dispatch("traceSelect", trace);
    }

    function handlePageChange(page) {
        if (page >= 1 && page <= totalPages && page !== currentPage) {
            dispatch("pageChange", page);
        }
    }

    function getPageNumbers() {
        const pages = [];
        const maxVisible = 5;
        
        if (totalPages <= maxVisible) {
            for (let i = 1; i <= totalPages; i++) {
                pages.push(i);
            }
        } else {
            const start = Math.max(1, currentPage - Math.floor(maxVisible / 2));
            const end = Math.min(totalPages, start + maxVisible - 1);
            
            for (let i = start; i <= end; i++) {
                pages.push(i);
            }
        }
        
        return pages;
    }
</script>

<div class="trace-list">
    <div class="list-header">
        <h3>Trace 列表</h3>
        <div class="list-info">
            共 {totalItems.toLocaleString()} 条记录
        </div>
    </div>

    {#if isLoading}
        <div class="loading-overlay">
            <div class="loader" />
            <span>加载中...</span>
        </div>
    {/if}

    {#if traces.length === 0 && !isLoading}
        <div class="empty-list">
            <i class="ri-file-list-3-line" />
            <p>没有找到符合条件的 Trace 记录</p>
        </div>
    {:else}
        <div class="table-wrapper">
            <table class="traces-table">
                <thead>
                    <tr>
                        <th>Trace ID</th>
                        <th>操作名称</th>
                        <th>状态</th>
                        <th>开始时间</th>
                        <th>持续时间</th>
                        <th>Spans 数量</th>
                    </tr>
                </thead>
                <tbody>
                    {#each traces as trace (trace.trace_id)}
                        <tr 
                            class="trace-row" 
                            on:click={() => handleTraceClick(trace)}
                            role="button"
                            tabindex="0"
                        >
                            <td class="trace-id">
                                <code>{trace.trace_id.slice(0, 8)}...</code>
                            </td>
                            <td class="operation-name">
                                {trace.name || "-"}
                            </td>
                            <td class="status">
                                <span class="status-badge {getStatusClass(trace.status)}">
                                    <i class="{getStatusIcon(trace.status)}" />
                                    {trace.status}
                                </span>
                            </td>
                            <td class="start-time">
                                <FormattedDate date={trace.start_time} />
                            </td>
                            <td class="duration">
                                {formatDuration(trace.duration)}
                            </td>
                            <td class="span-count">
                                {trace.span_count || 1}
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>

        <!-- 分页控件 -->
        {#if totalPages > 1}
            <div class="pagination">
                <button 
                    type="button"
                    class="btn btn-sm btn-secondary"
                    disabled={currentPage === 1}
                    on:click={() => handlePageChange(currentPage - 1)}
                >
                    <i class="ri-arrow-left-line" />
                    上一页
                </button>

                <div class="page-numbers">
                    {#each getPageNumbers() as page}
                        <button 
                            type="button"
                            class="btn btn-sm {page === currentPage ? 'btn-primary' : 'btn-secondary'}"
                            on:click={() => handlePageChange(page)}
                        >
                            {page}
                        </button>
                    {/each}
                </div>

                <button 
                    type="button"
                    class="btn btn-sm btn-secondary"
                    disabled={currentPage === totalPages}
                    on:click={() => handlePageChange(currentPage + 1)}
                >
                    下一页
                    <i class="ri-arrow-right-line" />
                </button>
            </div>
        {/if}
    {/if}
</div>

<style>
    .trace-list {
        background: var(--baseColor);
        border-radius: var(--baseRadius);
        border: 1px solid var(--baseAlt2Color);
        position: relative;
    }

    .list-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        border-bottom: 1px solid var(--baseAlt2Color);
    }

    .list-header h3 {
        margin: 0;
        font-size: 1.1em;
        color: var(--txtPrimaryColor);
    }

    .list-info {
        font-size: 0.875em;
        color: var(--txtHintColor);
    }

    .loading-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(255, 255, 255, 0.8);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 12px;
        z-index: 10;
        border-radius: var(--baseRadius);
    }

    .empty-list {
        text-align: center;
        padding: 60px 20px;
        color: var(--txtHintColor);
    }

    .empty-list i {
        font-size: 3em;
        margin-bottom: 16px;
        opacity: 0.5;
    }

    .table-wrapper {
        overflow-x: auto;
    }

    .traces-table {
        width: 100%;
        border-collapse: collapse;
    }

    .traces-table th {
        background: var(--baseAlt1Color);
        padding: 12px 16px;
        text-align: left;
        font-weight: 600;
        color: var(--txtPrimaryColor);
        border-bottom: 1px solid var(--baseAlt2Color);
        font-size: 0.875em;
    }

    .trace-row {
        cursor: pointer;
        transition: background-color 0.2s ease;
    }

    .trace-row:hover {
        background: var(--baseAlt1Color);
    }

    .traces-table td {
        padding: 12px 16px;
        border-bottom: 1px solid var(--baseAlt2Color);
        font-size: 0.875em;
    }

    .trace-id code {
        background: var(--baseAlt1Color);
        padding: 2px 6px;
        border-radius: 3px;
        font-family: monospace;
        font-size: 0.8em;
    }

    .operation-name {
        font-weight: 500;
        color: var(--txtPrimaryColor);
    }

    .status-badge {
        display: inline-flex;
        align-items: center;
        gap: 4px;
        padding: 4px 8px;
        border-radius: 12px;
        font-size: 0.75em;
        font-weight: 500;
    }

    .status-success {
        background: rgba(34, 197, 94, 0.1);
        color: var(--successColor);
    }

    .status-error {
        background: rgba(239, 68, 68, 0.1);
        color: var(--dangerColor);
    }

    .status-cancelled {
        background: rgba(156, 163, 175, 0.1);
        color: var(--txtHintColor);
    }

    .status-unknown {
        background: rgba(156, 163, 175, 0.1);
        color: var(--txtHintColor);
    }

    .duration {
        font-family: monospace;
        color: var(--txtHintColor);
    }

    .span-count {
        text-align: center;
        color: var(--txtHintColor);
    }

    .pagination {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 8px;
        padding: 20px;
        border-top: 1px solid var(--baseAlt2Color);
    }

    .page-numbers {
        display: flex;
        gap: 4px;
    }

    @media (max-width: 768px) {
        .list-header {
            flex-direction: column;
            gap: 8px;
            align-items: flex-start;
        }

        .traces-table th,
        .traces-table td {
            padding: 8px 12px;
        }

        .pagination {
            flex-direction: column;
            gap: 12px;
        }

        .page-numbers {
            flex-wrap: wrap;
            justify-content: center;
        }
    }
</style>
