// webui/src/features/jobs/components/JobsFilters.tsx
/**
 * JobsFilters 组件
 * 任务筛选器 - 与 UI 版本对齐
 */
import { useCallback } from 'react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import type { JobsFilter } from '../store'

interface JobsFiltersProps {
  filter: JobsFilter
  onChange: (filter: Partial<JobsFilter>) => void
  onClear: () => void
  className?: string
}

const STATUS_OPTIONS = [
  { value: 'all', label: 'All Statuses' },
  { value: 'pending', label: 'Pending' },
  { value: 'processing', label: 'Processing' },
  { value: 'completed', label: 'Completed' },
  { value: 'failed', label: 'Failed' },
]

const LIMIT_OPTIONS = [10, 20, 50, 100]

export function JobsFilters({ filter, onChange, onClear, className }: JobsFiltersProps) {
  const handleTopicChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      onChange({ topic: e.target.value })
    },
    [onChange]
  )

  const handleStatusChange = useCallback(
    (value: string) => {
      onChange({ status: value === 'all' ? '' : value })
    },
    [onChange]
  )

  const handleLimitChange = useCallback(
    (value: string) => {
      onChange({ limit: parseInt(value, 10) })
    },
    [onChange]
  )

  return (
    <div className={cn('flex flex-wrap items-end gap-2.5', className)}>
      <div className="space-y-1">
        <Label htmlFor="filter-topic" className="text-xs font-medium">Topic</Label>
        <Input
          id="filter-topic"
          placeholder="Filter by topic..."
          value={filter.topic}
          onChange={handleTopicChange}
          className="h-[38px] w-[180px]"
        />
      </div>

      <div className="space-y-1">
        <Label htmlFor="filter-status" className="text-xs font-medium">Status</Label>
        <Select value={filter.status || 'all'} onValueChange={handleStatusChange}>
          <SelectTrigger className="h-[38px] w-[140px]">
            <SelectValue placeholder="All Statuses" />
          </SelectTrigger>
          <SelectContent>
            {STATUS_OPTIONS.map((opt) => (
              <SelectItem key={opt.value} value={opt.value}>
                {opt.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-1">
        <Label htmlFor="filter-limit" className="text-xs font-medium">Per Page</Label>
        <Select value={String(filter.limit)} onValueChange={handleLimitChange}>
          <SelectTrigger className="h-[38px] w-[80px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {LIMIT_OPTIONS.map((limit) => (
              <SelectItem key={limit} value={String(limit)}>
                {limit}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="space-y-1">
        <Label className="text-xs">&nbsp;</Label>
        <Button variant="secondary" size="sm" className="h-[38px]" onClick={onClear}>
          Clear
        </Button>
      </div>
    </div>
  )
}

// ui/src/components/jobs/JobsFilters.svelte
<script>
    import { createEventDispatcher } from "svelte";

    export let filter = { topic: "", status: "", limit: 20, offset: 0 };

    const dispatch = createEventDispatcher();

    const statusOptions = [
        { value: "", label: "All Statuses" },
        { value: "pending", label: "Pending" },
        { value: "processing", label: "Processing" },
        { value: "completed", label: "Completed" },
        { value: "failed", label: "Failed" },
    ];

    const limitOptions = [10, 20, 50, 100];

    function handleChange() {
        dispatch("change", filter);
    }

    function clearFilters() {
        filter = { topic: "", status: "", limit: 20, offset: 0 };
        dispatch("change", filter);
    }
</script>

<div class="filters flex flex-gap-10 flex-wrap">
    <div class="form-field form-field-sm">
        <label for="filter-topic">Topic</label>
        <input
            type="text"
            id="filter-topic"
            placeholder="Filter by topic..."
            bind:value={filter.topic}
            on:change={handleChange}
        />
    </div>

    <div class="form-field form-field-sm">
        <label for="filter-status">Status</label>
        <select
            id="filter-status"
            bind:value={filter.status}
            on:change={handleChange}
        >
            {#each statusOptions as opt}
                <option value={opt.value}>{opt.label}</option>
            {/each}
        </select>
    </div>

    <div class="form-field form-field-sm">
        <label for="filter-limit">Per Page</label>
        <select
            id="filter-limit"
            bind:value={filter.limit}
            on:change={handleChange}
        >
            {#each limitOptions as limit}
                <option value={limit}>{limit}</option>
            {/each}
        </select>
    </div>

    <div class="form-field form-field-sm">
        <label>&nbsp;</label>
        <button
            type="button"
            class="btn btn-sm btn-secondary"
            on:click={clearFilters}
        >
            Clear
        </button>
    </div>
</div>

<style>
    .filters {
        margin-bottom: 0.5rem;
    }

    .form-field {
        min-width: 120px;
    }

    .form-field label {
        display: block;
        font-size: 0.7rem;
        color: var(--txtHintColor);
        margin-bottom: 0.25rem;
    }
</style>
