// ui-v2/src/features/analytics/components/TopList.tsx
import { useTranslation } from 'react-i18next'
import { cn } from '@/lib/utils'
import { Search, Share2, MousePointer, Link } from 'lucide-react'

interface TopListItem {
  [key: string]: unknown
}

interface TopListProps {
  items: TopListItem[]
  labelKey?: string
  valueKey?: string
  secondaryKey?: string | null
  secondaryLabel?: string
  showType?: boolean
  typeKey?: string
  showPercent?: boolean
  total?: number
  className?: string
}

function formatNumber(value: unknown): string {
  if (value === null || value === undefined) return '-'
  const num = Number(value)
  if (isNaN(num)) return String(value)
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1) + 'M'
  }
  if (num >= 1000) {
    return (num / 1000).toFixed(1) + 'K'
  }
  return num.toString()
}

function getPercent(value: unknown, total: number): string {
  if (!total || !value) return '0%'
  const num = Number(value)
  if (isNaN(num)) return '0%'
  return ((num / total) * 100).toFixed(1) + '%'
}

function getTypeIcon(type: string) {
  switch (type) {
    case 'search':
      return <Search className="w-4 h-4" />
    case 'social':
      return <Share2 className="w-4 h-4" />
    case 'direct':
      return <MousePointer className="w-4 h-4" />
    default:
      return <Link className="w-4 h-4" />
  }
}

export function TopList({
  items,
  labelKey = 'label',
  valueKey = 'value',
  secondaryKey = null,
  secondaryLabel = '',
  showType = false,
  typeKey = 'type',
  showPercent = false,
  total = 0,
  className,
}: TopListProps) {
  const { t } = useTranslation()

  if (items.length === 0) {
    return <div className={cn('text-center py-8 text-muted-foreground', className)}>暂无数据</div>
  }

  return (
    <div className={cn('flex flex-col gap-2', className)}>
      {items.map((item, i) => (
        <div key={i} className="flex items-center gap-2 p-2 bg-muted/50 rounded-md">
          <span className="w-6 h-6 rounded-full bg-muted flex items-center justify-center text-xs font-semibold flex-shrink-0">
            {i + 1}
          </span>
          <div className="flex-1 min-w-0 flex items-center gap-2">
            {showType && (
              <span className="text-muted-foreground flex-shrink-0">
                {getTypeIcon(String(item[typeKey] || ''))}
              </span>
            )}
            <span className="text-sm truncate" title={String(item[labelKey] || '')}>
              {String(item[labelKey]) || '(unknown)'}
            </span>
          </div>
          <div className="flex items-center gap-2 flex-shrink-0">
            <span className="font-semibold text-sm">{formatNumber(item[valueKey])}</span>
            {secondaryKey && item[secondaryKey] !== undefined && (
              <span className="text-xs text-muted-foreground">
                {secondaryLabel}: {formatNumber(item[secondaryKey])}
              </span>
            )}
            {showPercent && (
              <span className="text-xs text-muted-foreground min-w-[45px] text-right">
                {getPercent(item[valueKey], total)}
              </span>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}

// ui/src/components/analytics/TopList.svelte
<script>
    export let items = [];
    export let labelKey = "label";
    export let valueKey = "value";
    export let secondaryKey = null;
    export let secondaryLabel = "";
    export let showType = false;
    export let typeKey = "type";
    export let showPercent = false;
    export let total = 0;

    function formatNumber(value) {
        if (value === null || value === undefined) return "-";
        if (value >= 1000000) {
            return (value / 1000000).toFixed(1) + "M";
        }
        if (value >= 1000) {
            return (value / 1000).toFixed(1) + "K";
        }
        return value.toString();
    }

    function getPercent(value) {
        if (!total || !value) return "0%";
        return ((value / total) * 100).toFixed(1) + "%";
    }

    function getTypeIcon(type) {
        switch (type) {
            case "search":
                return "ri-search-line";
            case "social":
                return "ri-share-line";
            case "direct":
                return "ri-cursor-line";
            default:
                return "ri-link";
        }
    }
</script>

<div class="top-list">
    {#if items.length === 0}
        <div class="empty-state">暂无数据</div>
    {:else}
        {#each items as item, i}
            <div class="list-item">
                <span class="item-rank">{i + 1}</span>
                <div class="item-content">
                    {#if showType}
                        <i class={getTypeIcon(item[typeKey])} />
                    {/if}
                    <span class="item-label" title={item[labelKey]}>
                        {item[labelKey] || "(unknown)"}
                    </span>
                </div>
                <div class="item-values">
                    <span class="item-value">{formatNumber(item[valueKey])}</span>
                    {#if secondaryKey && item[secondaryKey] !== undefined}
                        <span class="item-secondary">
                            {secondaryLabel}: {formatNumber(item[secondaryKey])}
                        </span>
                    {/if}
                    {#if showPercent}
                        <span class="item-percent">{getPercent(item[valueKey])}</span>
                    {/if}
                </div>
            </div>
        {/each}
    {/if}
</div>

<style>
    .top-list {
        display: flex;
        flex-direction: column;
        gap: 0.5rem;
    }
    .empty-state {
        text-align: center;
        padding: 2rem;
        color: var(--txtHintColor);
    }
    .list-item {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem;
        background: var(--baseColor);
        border-radius: var(--smRadius);
    }
    .item-rank {
        width: 24px;
        height: 24px;
        border-radius: 50%;
        background: var(--baseAlt2Color);
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 0.75rem;
        font-weight: 600;
        flex-shrink: 0;
    }
    .item-content {
        flex: 1;
        min-width: 0;
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }
    .item-content i {
        color: var(--txtHintColor);
        flex-shrink: 0;
    }
    .item-label {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        font-size: 0.875rem;
    }
    .item-values {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        flex-shrink: 0;
    }
    .item-value {
        font-weight: 600;
        font-size: 0.875rem;
    }
    .item-secondary {
        font-size: 0.75rem;
        color: var(--txtHintColor);
    }
    .item-percent {
        font-size: 0.75rem;
        color: var(--txtHintColor);
        min-width: 45px;
        text-align: right;
    }
</style>
