// ui/src/components/records/RecordFieldValue.svelte
<script>
    import tooltip from "@/actions/tooltip";
    import CopyIcon from "@/components/base/CopyIcon.svelte";
    import FormattedDate from "@/components/base/FormattedDate.svelte";
    import TinyMCE from "@/components/base/TinyMCE.svelte";
    import RecordFileThumb from "@/components/records/RecordFileThumb.svelte";
    import RecordInfo from "@/components/records/RecordInfo.svelte";
    import GeoPointValue from "@/components/records/fields/GeoPointValue.svelte";
    import { superuser } from "@/stores/superuser";
    import CommonHelper from "@/utils/CommonHelper";

    export let record;
    export let field;
    export let short = false;

    $: rawValue = record?.[field.name];
</script>

{#if field.primaryKey}
    <div class="label">
        <CopyIcon value={rawValue} />
        <div class="txt txt-ellipsis">{rawValue}</div>
    </div>
    {#if record.collectionName == "_superusers" && record.id == $superuser.id}
        <span class="label label-warning">You</span>
    {/if}
{:else if field.type === "json"}
    {@const stringifiedJson = CommonHelper.trimQuotedValue(JSON.stringify(rawValue)) || '""'}
    {#if short}
        <span class="txt txt-ellipsis">
            {CommonHelper.truncate(stringifiedJson)}
        </span>
    {:else}
        <span class="txt">
            {CommonHelper.truncate(stringifiedJson, 500, true)}
        </span>
        {#if stringifiedJson.length > 500}
            <CopyIcon value={JSON.stringify(rawValue, null, 2)} />
        {/if}
    {/if}
{:else if CommonHelper.isEmpty(rawValue)}
    <span class="txt-hint">N/A</span>
{:else if field.type === "bool"}
    <span class="label" class:label-success={!!rawValue}>{rawValue ? "True" : "False"}</span>
{:else if field.type === "number"}
    <span class="txt">{rawValue}</span>
{:else if field.type === "url"}
    <a
        class="txt-ellipsis"
        href={rawValue}
        target="_blank"
        rel="noopener noreferrer"
        use:tooltip={"Open in new tab"}
        on:click|stopPropagation
    >
        {CommonHelper.truncate(rawValue)}
    </a>
{:else if field.type === "editor"}
    {#if short}
        <span class="txt">
            {CommonHelper.truncate(CommonHelper.plainText(rawValue), 195)}
        </span>
    {:else}
        <TinyMCE
            cssClass="tinymce-preview"
            conf={{
                branding: false,
                promotion: false,
                menubar: false,
                statusbar: false,
                min_height: 30,
                height: 59,
                max_height: 500,
                autoresize_bottom_margin: 5,
                resize: false,
                content_style: "body { font-size: 14px }",
                toolbar: "",
                plugins: ["autoresize"],
                skin: "pocketbase",
            }}
            value={rawValue}
            disabled
        />
    {/if}
{:else if field.type === "date" || field.type === "autodate"}
    <FormattedDate date={rawValue} />
{:else if field.type === "select"}
    <div class="inline-flex">
        {#each CommonHelper.toArray(rawValue) as item, i (i + item)}
            <span class="label">{item}</span>
        {/each}
    </div>
{:else if field.type === "relation"}
    {@const relations = CommonHelper.toArray(rawValue)}
    {@const expanded = CommonHelper.toArray(record?.expand?.[field.name])}
    {@const relLimit = short ? 20 : 500}
    <div class="inline-flex">
        {#if expanded.length}
            {#each expanded.slice(0, relLimit) as item, i (i + item)}
                <span class="label">
                    <RecordInfo record={item} />
                </span>
            {/each}
        {:else}
            {#each relations.slice(0, relLimit) as id}
                <span class="label">{id}</span>
            {/each}
        {/if}
        {#if relations.length > relLimit}
            ...
        {/if}
    </div>
{:else if field.type === "file"}
    {@const files = CommonHelper.toArray(rawValue)}
    {@const filesLimit = short ? 10 : 500}
    <div class="inline-flex" class:multiple={field.maxSelect != 1}>
        {#each files.slice(0, filesLimit) as filename, i (i + filename)}
            <RecordFileThumb {record} {filename} size="sm" />
        {/each}
        {#if files.length > filesLimit}
            ...
        {/if}
    </div>
{:else if field.type === "geoPoint"}
    <div class="label"><GeoPointValue value={rawValue} /></div>
{:else if field.type === "secret"}
    {@const maskedValue = rawValue ? (rawValue.length <= 8 ? "•".repeat(rawValue.length) : rawValue.slice(0, 3) + "•".repeat(Math.min(rawValue.length - 6, 10)) + rawValue.slice(-3)) : ""}
    <span class="txt txt-hint" use:tooltip={"Secret field - hidden"}>
        {maskedValue || "N/A"}
    </span>
{:else if short}
    <span class="txt txt-ellipsis" title={CommonHelper.truncate(rawValue)}>
        {CommonHelper.truncate(rawValue)}
    </span>
{:else}
    <div class="block txt-break fallback-block">{rawValue}</div>
{/if}

<style>
    .fallback-block {
        max-height: 100px;
        overflow: auto;
    }
    .inline-flex {
        max-width: 100%;
    }
</style>

// ui-v2/src/features/records/components/RecordFieldValue.tsx
/**
 * 记录字段值展示组件
 * 根据字段类型渲染不同的值展示方式
 */
import { ExternalLink, Copy, Check } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Button } from '@/components/ui/button'
import { truncate, toArray, isEmpty, plainText, maskSecret } from '@/lib/utils'
import { formatDate } from '@/lib/dateUtils'
import { RecordInfo } from './RecordInfo'
import { RecordFileThumb } from './RecordFileThumb'
import type { RecordModel, SchemaField } from 'pocketbase'

interface RecordFieldValueProps {
  record: RecordModel
  field: SchemaField & { primaryKey?: boolean }
  short?: boolean
}

export function RecordFieldValue({ record, field, short = false }: RecordFieldValueProps) {
  const [copied, setCopied] = useState(false)
  const rawValue = record?.[field.name]

  const handleCopy = async (value: string) => {
    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // ignore
    }
  }

  // 主键字段
  if (field.primaryKey) {
    return (
      <div className="inline-flex items-center gap-1">
        <Button
          variant="ghost"
          size="icon"
          className="h-5 w-5"
          onClick={() => handleCopy(rawValue as string)}
        >
          {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
        </Button>
        <span className="truncate font-mono text-xs">{rawValue as string}</span>
      </div>
    )
  }

  // JSON 字段
  if (field.type === 'json') {
    const stringifiedJson = JSON.stringify(rawValue) || '""'
    if (short) {
      return <span className="truncate text-sm">{truncate(stringifiedJson)}</span>
    }
    return (
      <div className="inline-flex items-center gap-1">
        <span className="text-sm">{truncate(stringifiedJson, 500, true)}</span>
        {stringifiedJson.length > 500 && (
          <Button
            variant="ghost"
            size="icon"
            className="h-5 w-5"
            onClick={() => handleCopy(JSON.stringify(rawValue, null, 2))}
          >
            {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
          </Button>
        )}
      </div>
    )
  }

  // 空值
  if (isEmpty(rawValue)) {
    return <span className="text-muted-foreground text-sm">N/A</span>
  }

  // 布尔字段
  if (field.type === 'bool') {
    return <Badge variant={rawValue ? 'default' : 'secondary'}>{rawValue ? 'True' : 'False'}</Badge>
  }

  // 数字字段
  if (field.type === 'number') {
    return <span className="text-sm">{rawValue as number}</span>
  }

  // URL 字段
  if (field.type === 'url') {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <a
              className="truncate text-sm text-primary hover:underline inline-flex items-center gap-1"
              href={rawValue as string}
              target="_blank"
              rel="noopener noreferrer"
              onClick={(e) => e.stopPropagation()}
            >
              {truncate(rawValue as string)}
              <ExternalLink className="h-3 w-3" />
            </a>
          </TooltipTrigger>
          <TooltipContent>在新标签页中打开</TooltipContent>
        </Tooltip>
      </TooltipProvider>
    )
  }

  // 富文本编辑器字段
  if (field.type === 'editor') {
    if (short) {
      return <span className="text-sm">{truncate(plainText(rawValue as string), 195)}</span>
    }
    return (
      <div
        className="prose prose-sm max-w-none max-h-[100px] overflow-auto"
        dangerouslySetInnerHTML={{ __html: rawValue as string }}
      />
    )
  }

  // 日期字段
  if (field.type === 'date' || field.type === 'autodate') {
    return <span className="text-sm">{formatDate(rawValue as string)}</span>
  }

  // 选择字段
  if (field.type === 'select') {
    const items = toArray(rawValue)
    return (
      <div className="inline-flex flex-wrap gap-1">
        {items.map((item, i) => (
          <Badge key={`${i}-${item}`} variant="secondary">
            {item}
          </Badge>
        ))}
      </div>
    )
  }

  // 关联字段
  if (field.type === 'relation') {
    const relations = toArray(rawValue)
    const expanded = toArray(record?.expand?.[field.name])
    const relLimit = short ? 20 : 500

    return (
      <div className="inline-flex flex-wrap gap-1">
        {expanded.length > 0
          ? expanded.slice(0, relLimit).map((item, i) => (
              <Badge key={`${i}-${item.id}`} variant="outline">
                <RecordInfo record={item} />
              </Badge>
            ))
          : relations.slice(0, relLimit).map((id) => (
              <Badge key={id} variant="outline">
                {id}
              </Badge>
            ))}
        {relations.length > relLimit && <span>...</span>}
      </div>
    )
  }

  // 文件字段
  if (field.type === 'file') {
    const files = toArray(rawValue)
    const filesLimit = short ? 10 : 500

    return (
      <div className="inline-flex flex-wrap gap-1">
        {files.slice(0, filesLimit).map((filename, i) => (
          <RecordFileThumb key={`${i}-${filename}`} record={record} filename={filename} size="sm" />
        ))}
        {files.length > filesLimit && <span>...</span>}
      </div>
    )
  }

  // 地理坐标字段
  if (field.type === 'geoPoint') {
    const value = rawValue as { lon?: number; lat?: number }
    return (
      <Badge variant="outline">
        {value?.lon?.toFixed(6)}, {value?.lat?.toFixed(6)}
      </Badge>
    )
  }

  // Secret 字段
  if (field.type === 'secret') {
    const maskedValue = rawValue ? maskSecret(String(rawValue)) : ''
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <span className="text-muted-foreground font-mono text-xs">
              {maskedValue || 'N/A'}
            </span>
          </TooltipTrigger>
          <TooltipContent>
            <p>Secret field - hidden</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    )
  }

  // 默认文本展示
  if (short) {
    return (
      <span className="truncate text-sm" title={truncate(rawValue as string)}>
        {truncate(rawValue as string)}
      </span>
    )
  }

  return <div className="max-h-[100px] overflow-auto text-sm break-all">{rawValue as string}</div>
}
